### ISSUE TITLE
Ajouter un lien vers le dépôt en pied de page

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#12]
Ça pourrait être bien d'ajouter par défaut un lien vers le dépôt en pied de page pour montrer que c'est un logiciel libre. D'autres gens pourraient peut-être aider ou l'héberger aussi comme ça

**Comment by fallen** [comment]
Bonne idée, c'est fait via https://github.com/fallen/Pytition/commit/58ddbadef6dcbf6a19e84a039bb1913a52edd22f et https://github.com/fallen/Pytition/commit/d43c05547a552e7d792f7a1c34c9e927dce9d7bf
