### ISSUE TITLE
OpenGraph ne fonctionne pas correctement

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#14]
La preview ne semble pas être correcte sur facebook. Il n'affiche pas l'image et met en titre la description et non le titre.
Pourtant ça semble être correct d'après ça http://opengraphcheck.com/result.php?url=http%3A%2F%2Fpetition.antipub.org%2Fpetition%2F5%2F

**Comment by fallen** [comment]
Pour l'image je pense que c'est du au fait que Facebook n'a pas réussi à charger l'image la première fois qu'il a scrappé la page et ensuite il a mis cette erreur en cache.
Il faut changer le nom du fichier sur le serveur et dans la config de la pétition et re-demander à Facebook de scraper la page. Je ne vois pas trop d'autre solution.

**Comment by fallen** [comment]
Pour ce qui est du titre, ça me semble correct. A la fois sur opengraphcheck et sur Facebook.

**Comment by fallen** [comment]
Ah bah on dirait que ça marche maintenant sur Facebook l'image :)

**Comment by Dostoi** [comment]
Nickel :)
