### ISSUE TITLE
Pouvoir changer le nom de l'orga dans le texte sur les données personnelles

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#16]
Actuellement il est géré globalement ce qui donne ça :
"Vos données resteront strictement confidentielles et ne seront ni vendues ni échangées. Des informations sur cette campagne ainsi que d’autres actualités sur RAP vous seront envoyées si vous avez coché la case. Vous pouvez vous désinscrire à tout moment."

Sur la pétition pour la campagne stop pub vidéo alors qu'il faudrait pouvoir dire "d’autres actualités sur la campagne Stop Pub Vidéo vous"

**Comment by fallen** [comment]
A priori c'est bon maintenant ! via https://github.com/fallen/Pytition/commit/c87b30c7c9f234f0cbf2f9060d51026081618786
