### ISSUE TITLE
Ajout d'un bouton pour accéder directement à la pétition depuis sa page d'édition

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#17]
Actuellement pour visualiser les changements, il faut rentrer l'url de la pétition. Ça serait pratique d'ajouter un bouton pour accéder directement à la pétition depuis la page d'édition de la pétition et visualiser plus rapidement les changements effectués.

Je parle depuis cette page par exemple : http://petition.antipub.org/admin/petition/petition/2/change/

**Comment by fallen** [comment]
Ajouté par https://github.com/fallen/Pytition/commit/b015652d67292eceb217cb7a84ec372e99c7a577
