### ISSUE TITLE
Option pour renvoyer l'email de vérification

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#18]
Pouvoir renvoyer l'email de vérification à ceux qui ne l'ont pas eu serait pratique.

Pouvoir le faire depuis la page d'édition de l'objet signature, depuis les actions groupées de la liste des signatures et avec un bouton global pour le faire à toutes les signatures non validées.

**Comment by fallen** [comment]
Avec ces 3 modifications ça doit être bon je pense.
Au final j'ai plutôt mis un lien sur la page de modification de la pétition qui pointe vers la page qui liste les signatures et qui affiche seulement les signatures non confirmées de la-dite pétition. Plutôt qu'un bouton qui renverrai les mails.
Après, depuis la liste de signature, on peut cliquer sur "sélectionner tout" puis effectuer l'action de renvoie de mail.

**Comment by Dostoi** [comment]
Super, de pouvoir faire ça !
Pour le bouton permettant d'accéder directement à la liste des signatures non confirmés, je sais pas si c'est mieux là comme t'as ajouté un filtre sur la liste de signature. Ça "alourdi" un peu plus la page d'édition pour un gain pas énorme (ça fait économiser un clic)
