### ISSUE TITLE
Ajout d'un fonction de recherche pour les pétitions et les signatures

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#19]
Ça pourrait être pratique d'avoir une fonction de recherche pour les pétitions (pour un site qui en héberge plein) mais surtout (dans l'immédiat) pour les signatures.

Certaines personnes nous font remonter des soucis avec leurs signatures et c'est compliqué de vérifier si elles ont bien été enregistré dans l'état.

**Comment by fallen** [comment]
Peux-tu préciser comment tu verrai cette recherche de pétitions/signatures stp ?

**Comment by Dostoi** [comment]
C'est deux améliorations séparées, j'aurais du préciser plus.

Dans la page qui liste les signatures, ajouter un champ pour effectuer des recherches dans les signatures. Pour retrouver une signature en faisant une recherche sur les données enregistrées (nom, téléphone, mail,...).

Et dans la page listant les pétitions, ajouter un champ pour effectuer des recherches sur les pétitions. C'est pas hyper utile dans l'immédiat mais dans une vision long terme, ça pourra être utile si une instance du logiciel a beaucoup de pétition.

**Comment by fallen** [comment]
Peux-tu me dire si comme ça, ça te va ?

**Comment by Dostoi** [comment]
C'est exactement ça :)

Par contre ça semble ne pas marcher pour les pétitions. Si je tape "écran" par exemple, je n'obtiens rien.

Et peut-être juste changer le texte affiché entre parenthèse qui correspond au nombre total, pour mettre "Tout afficher" ou un truc du genre plutôt que "x résultats" qui fait doublon avec le x résultat de juste avant qui correspond au résultat de la rechercher lui.

**Comment by fallen** [comment]
Le souci avec "écran" c'est que dans la base de données c'est stocké en "&eacute;crans" du coup ça ne trouve pas. Je regarderai plus tard si je peux corriger ce genre de chose.
Pour l'histoire des résultats etc ça c'est une mécanique de Django-admin, ça serait pas mal de complications de changer ça du coup je préfère laisser tel quel.

**Comment by Dostoi** [comment]
Ça marche pas de soucis, c'est déjà super comme ça
