### ISSUE TITLE
get_json_data

### ISSUE THREAD

**Issue by jherve** [fallen/Pytition#2]
https://github.com/fallen/Pytition/blob/6ac19522df7faab4c9e8b45ef8bca4df3ea4c44e/pytition/petition/urls.py#L11

Si tu veux pouvoir récupérer du JSON, il me semble que ceci : http://www.django-rest-framework.org/api-guide/serializers/ est plus approprié pour bien gérer ça

(j'y ai pas touché mais c'est apparemment un des meilleurs packages Django et c'est pile fait pour ça, me semble-t-il)

**Comment by fallen** [comment]
Ce code n'existe plus et je ne sérialise pas de gros objets en Json
