### ISSUE TITLE
Ajout d'un bouton pour accéder directement aux signatures d'une pétition depuis sa page d'édition

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#20]
Ça pourrait être pratique de pouvoir accéder directement aux signatures (et que celles là) d'une pétition depuis sa page d'édition en ajoutant un bouton dans cette page.

**Comment by fallen** [comment]
On peut maintenant filtrer par pétition sur la page qui liste les signatures : https://petition.antipub.org/admin/petition/signature/
Mais aussi accéder aux signatures d'une pétition depuis la page d'édition d'une pétition
