### ISSUE TITLE
Valider sa nouvelle signature supprime ses signatures validées des autres pétitions

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#21]
Chaque personne ne peut avoir qu'une seule signature validée pour toutes les pétitions hébergées sur le même serveur.
Le fait de valider une nouvelle pétition va supprimer celle de l'ancienne.

Par exemple, je signe et valide une 1ere signature sur la pétition A.
Ensuite je signe la pétition B sans valider. Le logiciel va avoir 2 signatures m'appartenant, une validée, une non.
Lorsque je valide la signature de la pétition B, le logiciel supprime la signature de la pétition A et garde uniquement la signature de la pétition B.

**Comment by fallen** [comment]
Merci c'est réglé normalement !
