### ISSUE TITLE
Texte de demande de confirmation dépasse du cadre

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#22]
La fin de phrase de demande de confirmation de la signature atterris en dessous du cadre de droite sur ma configuration. (il manque la fin du mot signature)
Sur un écran de 1366*768 avec firefox 58.0.1 sous debian.

![capture du 2018-02-08 14-03-56](https://user-images.githubusercontent.com/7694864/35981339-4ed02ac8-0ced-11e8-9431-b9340f1c8af5.png)

**Comment by SylvainDe** [comment]
@fallen qui :scissors:  ce qui dépasse du cadre :)
