### ISSUE TITLE
Découpage des tâches entre models/views/forms

### ISSUE THREAD

**Issue by jherve** [fallen/Pytition#4]
https://github.com/fallen/Pytition/blob/6ac19522df7faab4c9e8b45ef8bca4df3ea4c44e/pytition/petition/views.py#L35

Je mets cette ligne un peu au pif mais dans l'ensemble tu fais un peu tout au même endroit et ça complexifie bcp les choses (tout en compliquant aussi le debug ...)

Il y a : 
* des trucs qui relèvent de la validation du modèle (genre le début de la fonction "confirm"), qui devraient plutot être dans une surcharge des fonctions "save" ou "clean" de ton modele "Signature"
* des trucs qui relèvent de la validation du formulaire (qui devrait d'ailleurs plutot être un objet Django que du HTML écrit à la main)
* le calcul de la page de redirection (là aussi avec les class based views c'est vachement plus simple)
* des trucs comportementaux (l'envoi de mail) qui devraient plutot être déclenchés en réaction à un signal (y a une nouvelle signature qu'a été ajoutée ? paf j'envoie le mail)
* etc, etc. 

(j'arrive pas à tout lister mais ce code fait vraiment bcp bcp bcp bcp trop de choses et respecte pas trop le découpage fonctionnel que t'es censé avoir entre model et view)

**Comment by fallen** [comment]
C'est plus propre maintenant Même si ya encore du gros boulot pour proprifier tout ça.
Mais je vois l'idée merci !
