### ISSUE TITLE
Installation issues and dev environment

### ISSUE THREAD

**Issue by Te-k** [fallen/Pytition#42]
Hi,

Few problems during the installation : 
* mysql_client : you need to install additional libraries, on ubuntu/debian : `sudo apt-get install python-dev default-libmysqlclient-dev`  (doc is [there](https://pypi.org/project/mysqlclient/))
* Pillow : I had some trouble installing `Pillow==5.1.0` because it was compiling the package, I am not really sure which dependency was needed. But I installed the last Pillow version 5.4.1 that does not require any compilation, so I suggest to migrate to this one. (doc is [there](https://pillow.readthedocs.io/en/3.0.x/installation.html#linux-installation) )

Regarding dev environment, the default database today is MySQL, I would suggest to have sqlite by default and to separate instructions for dev and prod installation in the README (maybe two separated readmes ?)

**Comment by fallen** [comment]
I just tried to install Pytition in a dev environment on a fresh Ubuntu 18.04 install, you need:

- sudo apt install git virtualenv libmariadbclient-dev python3-dev build-essential

**Comment by fallen** [comment]
About Pillow I suggest to just remove dependency to it as per issue https://github.com/fallen/Pytition/issues/46

**Comment by fallen** [comment]
I added instructions for contributors and a script to help new developers to jump in: https://github.com/fallen/Pytition/commit/ee86785a9198499a9330d314dedffe01cb1525ee

**Comment by fallen** [comment]
Do you think the issue is fixed now with https://github.com/fallen/Pytition/pull/69 ?

**Comment by Te-k** [comment]
Yes, thanks
