### ISSUE TITLE
Pas de migrations ?!

### ISSUE THREAD

**Issue by jherve** [fallen/Pytition#5]
Tu devrais avoir au moins une migration 0001_initial.py, t'as oublié de la pusher ?!

**Comment by fallen** [comment]
La coutume c'est de pusher la/les migration ?
Je pensais laisser la personne faire la migration initiale avec manage.py

**Comment by jherve** [comment]
Ah ouais ouais ouais ! 
Quand tu récupères ton bousin faut juste que t'aies à faire un "manage.py migrate", mais pas le "makemigrations" :)

**Comment by fallen** [comment]
ah d'accord, jvais regarder ça merci !

**Comment by fallen** [comment]
Corrigé par https://github.com/fallen/Pytition/commit/575d7ead2edc55f56445d3227ecc915ccdd76bfd
Merci !
