### ISSUE TITLE
Small mistake in dev_setup script

### ISSUE THREAD

**Issue by spiderweak** [fallen/Pytition#64]
The dev_setup script tests if a my.cnf file exists and prompts the user if he wants to change the configuration or to use its own.

The script does not react as expected.

If the user express its wish to keep its configuration. It generates one and pushes it at the end of the first.
If the user wants to change configuration. The configuration is kept but the scripts fails to connect (password error).

The dev_setup.sh script should actually do the opposite.

Also a password is taken from /home/petition/www which is probably a test folder but isn't created during the installation process.

I'm working on the script right now, a pull request should arrive soon.

**Comment by fallen** [comment]
You are right, thanks for spotting that!
Your first commit looks good to me, you can create a PR!

**Comment by fallen** [comment]
For the /home/petition/www maybe you missed this line https://github.com/fallen/Pytition/blob/master/dev/dev_setup.sh#L87 ? Or I have another bug?

**Comment by spiderweak** [comment]
No issue for this line, my mistake.
