### ISSUE TITLE
Trucs HTML-dependent dans le code des modèles

### ISSUE THREAD

**Issue by jherve** [fallen/Pytition#7]
https://github.com/fallen/Pytition/blob/6ac19522df7faab4c9e8b45ef8bca4df3ea4c44e/pytition/petition/models.py#L23

Ca me parait très très chelou d'avoir des trucs genre "HTMLField" dans le code des modèles ... C'est typiquement le genre de truc qui devrait être dans la définition du formulaire associé 

(bon, j'ai été voir dans la doc' de tinymce et ils disent que cette option est pour les "lazy developers" :p )

**Comment by fallen** [comment]
Ouais en gros j'aurai du mettre un TextField(widget=mon widget tinymce) selon toi ?

**Comment by jherve** [comment]
TextField tout court, et ensuite dans le formulaire que tu fais du coup en Django plutot qu'en HTML pour te simplifier la vie, c'est là que tu fais intervenir le widget=bidule truc 

C'est la philosophie habituelle (même s'il me semble avoir déjà vu des intégristes dire que ça devrait même pas être dans la déclaration du champ du formulaire mais carrément dans le template) et c'est confirmé par la doc : https://django-tinymce.readthedocs.io/en/latest/usage.html#using-the-widget

**Comment by fallen** [comment]
Tu me conseilles d'utiliser ça donc : https://docs.djangoproject.com/fr/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides pour overrider le widget par défaut du panneau admin, et mettre un TinyMCE au lieu du textarea classique ?

**Comment by jherve** [comment]
> Cet attribut fournit une solution « à la va-vite »

Oui, parfait :p 
Plus sérieusement, oui, ça a l'air d'être une bonne solution, si le but est d'avoir ça uniquement dans l'interface d'admin (si le but est pas d'avoir des utilisateurs qui pourraient ajouter des pétitions eux mêmes)

**Comment by fallen** [comment]
Oui, a priori l'objet Pétition n'est créé/modifié *que* par les admins du site

**Comment by fallen** [comment]
Ya quoi de mieux du coup si c'est pas "à la va-vite" :p

**Comment by jherve** [comment]
Faire ton propre  ModelAdmin.form ?

Ca me parait complètement overkill dans ce cas là mais j'imagine que c'est la solution qu'ils préconisent

**Comment by fallen** [comment]
Ouais ok je vois

**Comment by fallen** [comment]
Je n'utilise plus l'interface Admin de Django.
Et je garde les HTMLField() pour le moment.
