### ISSUE TITLE
Mettre un titre pour savoir à quoi correspond chaque champ de texte

### ISSUE THREAD

**Issue by Dostoi** [fallen/Pytition#9]
Lors de la création d'une nouvelle pétition, on ne peut pas savoir à quoi correspond chaque champ de texte. L'ajout d'un titre permettrait de le savoir.

**Comment by fallen** [comment]
En effet, c'est fixé par https://github.com/fallen/Pytition/commit/181b9ce300999fefb241e7af226017774674ea07
Merci :)

**Comment by Dostoi** [comment]
Je l'aurai bien ajouté pour les champs de textes aussi (les 2 premiers qui correspondent au titres et au contenu de la page + celui qui correspond à la zone de droite d'après mes tests et celui qui correspond au pied de page aussi)

**Comment by fallen** [comment]
Oops j'avais oublié d'executer ```python3 manage.py collectstatic``` c'est fait :)
